name: 'Tembo Database Branching Action'
description: 'Setup Database branching on your Tembo database instances'
author: 'Tembo'
branding:
  icon: database
  color: white

# todo: Add better more descriptive descriptions for inputs
inputs:
  action:
    description: 'Action task to perform (branch/delete)'
    default: 'branch'
  tembo-api-endpoint:
    description: 'The Tembo API you wish to interact with'
    default: 'https://api.tembo.io'
  org-id:
    description: 'The Tembo organization id associated with your account'
  instance-id:
    description: 'The Tembo id of the instance you wish to branch'
  instance-name:
    description: 'The name of your new branched instance.  Default is a randomly generated name'
  tembo-token:
    description: 'The Tembo JWT token used to access your organization'
  environment:
    description: 'The environment you wish to deploy the branched instance to: eg. dev/stanging/prod'
    default: 'prod'
  polling-interval:
    description: 'The interval polling the Tembo API endpoint (type Number)'
    default: '5000'
  max-polling-attempts:
    description: 'Maximum number of attempts to check the status through the Tembo API endpoint (type Number)'
    default: '60'

outputs:
  instance_id:
    description: 'The instance ID of the new Tembo branched instance'
  instance_name:
    description: 'The instance name of the Tembo branched instance'
  host:
    description: 'The instance host address of the Tembo branched instance'
  port:
    description: 'The instance port number for the connection to the Tembo branched instance'
  user:
    description: 'The username for the connection, base64 encoded'
  password:
    description: 'The password for the connection, base64 encoded'
  database_url:
    description: 'The full database connection URI without the database'

runs:
  using: 'node20'
  main: 'lib/main.js'
